name: OraxenNature
version: 1.6.0
main: it.hydr4.oraxennature.OraxenNature
api-version: 1.20
depend:
  - Oraxen
commands:
  oraxennature:
    description: OraxenNature commands
    usage: /<command> [args]
    aliases: [on]
    permission: oraxennature.admin
permissions:
  oraxennature.admin:
    description: Allows access to all OraxenNature admin commands.
    default: op
    children:
      oraxennature.reload: true
      oraxennature.set: true
      oraxennature.get: true
      oraxennature.debug: true
  oraxennature.reload:
    description: Allows reloading OraxenNature configurations.
    default: op
  oraxennature.set:
    description: Allows setting OraxenNature configuration values in-game.
    default: op
  oraxennature.get:
    description: Allows getting OraxenNature configuration values in-game.
    default: op
  oraxennature.debug:
    description: Allows toggling OraxenNature debug mode.
    default: op